import type { UserConfig } from '@commitlint/types';

const Configuration: UserConfig = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    // some automated commits generated by tools like semantic-release and dependabot
    // may exceed the default max length value of 100
    // so we need to increase it to 200 and change it to a warning
    'body-max-line-length': [1, 'always', 200],
    // allow all cases in the title
    'subject-case': [0],
  },
  ignores: [
    // ignore merge branches commits
    (commit) => commit.startsWith('Merge branches'),
  ],
};

export default Configuration;
