# list all services here, just as databases
# apps are listed in `docker-compose.yml`
# to run a service in devcontainer only or production only, use profiles
# https://docs.docker.com/compose/how-tos/profiles/

services:
  app-name-db:
    # to connect to this database from another container use the service's name and the container port
    # i.e `app-name-db:5432`
    # to connect from the host, use the host's port, i.e. `localhost:5433`
    # by default docker compose name the container as `<projectName>-<image-name>-<n>`
    container_name: impactor-app-name-db
    image: postgres:18-alpine
    restart: unless-stopped
    volumes:
      # postgres v18+ in docker stores data in `/var/lib/postgresql/<version>/docker`
      # to support multi version in the samne volume
      # before v18: `/var/lib/postgresql/data`
      # to use the old path, set env `PGDATA: /var/lib/postgresql/data`
      # https://github.com/docker-library/postgres/pull/1259
      - app-name-postgres:/var/lib/postgresql
      # run this init script when postgres starts
      # if the volume is not empty when building the image, scripts will be skipped
      # either run the container and execute them manually or remove the volume and build again
      # https://hub.docker.com/_/postgres -> Initialization scripts
      - ./docker-scripts/app-name/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    # allow external connections
    # equivalent to executing `postgres -i`
    # also see `environment.POSTGRES_HOST_AUTH_METHOD`
    # todo: allow external connections from the host only, not over network
    command: postgres -c "listen_addresses=*"
    # todo: use .env for dev and prod environments
    environment:
      POSTGRES_PASSWORD: ${APP_NAME_DB_PASSWORD:-postgres}
      POSTGRES_USER: ${APP_NAME_DB_USER:-postgres}
      # equivalent to modifying `pg_hba.conf` to trust connections
      POSTGRES_HOST_AUTH_METHOD: md5
      # POSTGRES_DB: postgres
    # to expose the container's port create a docker compose override file
    # any other container can access this container ports directly as long as both containers are in the same network
    ports:
      # use different port on the host other than the default one
      # to avoid a potential conflict if a database is installed there
      # the port is bound to "127.0.0.1" to accept connections from the host only, not from external network
      - "127.0.0.1:5433:5432"
    networks:
      - impactor-network
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  app-name-pgAdmin:
    container_name: impactor-app-name-pgAdmin
    image: dpage/pgadmin4:2025-05-27-1
    restart: unless-stopped
    ports:
      - "127.0.0.1:5050:5050"
    environment:
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_EMAIL: ${APP_NAME_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${APP_NAME_PGADMIN_PASSWORD}
    volumes:
      - app-name-pgadmin:/var/lib/pgadmin
        # adding Postgres container to pgAdmin severs
      - ./docker-scripts/app-name/pg-admin/servers.json:/pgadmin4/servers.json:ro
    networks:
      - impactor-network

  nginx:
    image: nginx
    container_name: impactor-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # nginx.conf example:
      # server {
      #   server_name example.com;
      #   location / {
      #      # if the app is running inside a container in the same netwwork, use the container name
      #      # if the app is running in the host, i.e. not in a container, use `http://host.docker.internal`
      #      proxy_pass http://cms-ui:4200;
      #   }
      # }
      - ~/data/impactor/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # allows the docker to access the host,
    # this allows nginx inside the container to forword the request to an app that is running in the host (not in container)
    # using http://host.docker.internal (the host) instead of http://localhost (the container)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - impactor-network

volumes:
  app-name-postgres:
  app-name-pgadmin:
  corepack-cache:
    driver: local
  pnpm-store:
    driver: local
  caddy_data:
  caddy_config:

networks:
  impactor-network:
    driver: bridge
