# list of available variants:
# https://mcr.microsoft.com/v2/devcontainers/typescript-node/tags/list
ARG VARIANT=latest

FROM mcr.microsoft.com/devcontainers/javascript-node:${VARIANT}

# install `act` to run Github actions locally
# https://nektosact.com/installation/index.html
# todo: act needs that docker to be installed and run inside the devContainer
# to configure act create `~/.config/act/actrc` file
# https://github.com/nektos/act#configuration
RUN curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/nektos/act/master/install.sh | bash


# install Docker
# also, add `features["docker-in-docker"]` in devcontainer.json
# RUN apt-get update && \
#     apt-get install -y docker.io && \
#     apt-get clean

# # Install Docker CLI -> use DinD feature in devcontainer.json
# # --no-install-recommends: Avoids installing unnecessary dependencies, keeping the image smaller
# RUN apt-get update && \
#     apt-get install -y --no-install-recommends docker.io && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/*


# # Docker compose
# RUN DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker} \
#     mkdir -p $DOCKER_CONFIG/cli-plugins && \
#     curl -sSL https://github.com/docker/compose/releases/download/v2.32.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose && \
#     chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose