name: CommitLint Workflow

on:
  workflow_call:

jobs:
  commitLint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v6
      - uses: wagoid/commitlint-github-action@v6
